### ISSUE TITLE
const string &

### ISSUE THREAD

**Issue by zRrrGet** [cyb3r-b4stard/fsa-to-regexp#1]
https://github.com/cyb3r-b4stard/fsa-to-regexp/blob/b38bca1059f7eeeaa9e7a524e1077664109ea201/main.cpp#L215

**Comment by cyb3r-b4stard** [comment]
Я твой рот наоборот, чшорт

**Comment by zRrrGet** [comment]
решай таску

**Comment by zRrrGet** [comment]
всмысле
